#############################################################################
# Makefile for building: ui_des
# Generated by qmake (2.01a) (Qt 4.7.1) on: ?? 5? 28 18:38:45 2023
# Project:  ui_des.pro
# Template: app
# Command: /opt/qt-4.7.1/bin/qmake -o Makefile ui_des.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qt-4.7.1/mkspecs/qws/linux-arm-g++ -I. -I/opt/qt-4.7.1/include/QtCore -I/opt/qt-4.7.1/include/QtNetwork -I/opt/qt-4.7.1/include/QtGui -I/opt/qt-4.7.1/include -I. -I.
LINK          = arm-linux-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qt-4.7.1/lib
LIBS          = $(SUBLIBS)  -L/opt/qt-4.7.1/lib -lQtGui -L/usr/local/tslib/lib -L/opt/qt-4.7.1/lib -lQtNetwork -lQtCore -lpthread 
AR            = arm-linux-ar cqs
RANLIB        = 
QMAKE         = /opt/qt-4.7.1/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		config_widget.cpp \
		keyboarddlg.cpp \
		mylinedit.cpp \
		mywidget.cpp \
		valve.cpp \
		mypid.cpp \
		mybutton.cpp \
		myi2c.cpp \
		mesdialog.cpp \
		pwmqthread.cpp moc_mainwindow.cpp \
		moc_config_widget.cpp \
		moc_keyboarddlg.cpp \
		moc_mylinedit.cpp \
		moc_mywidget.cpp \
		moc_mybutton.cpp \
		moc_mesdialog.cpp \
		moc_pwmqthread.cpp \
		qrc_image.cpp
OBJECTS       = main.o \
		mainwindow.o \
		config_widget.o \
		keyboarddlg.o \
		mylinedit.o \
		mywidget.o \
		valve.o \
		mypid.o \
		mybutton.o \
		myi2c.o \
		mesdialog.o \
		pwmqthread.o \
		moc_mainwindow.o \
		moc_config_widget.o \
		moc_keyboarddlg.o \
		moc_mylinedit.o \
		moc_mywidget.o \
		moc_mybutton.o \
		moc_mesdialog.o \
		moc_pwmqthread.o \
		qrc_image.o
DIST          = png/bt_off.png \
		png/bt_on.png \
		/opt/qt-4.7.1/mkspecs/common/g++.conf \
		/opt/qt-4.7.1/mkspecs/common/unix.conf \
		/opt/qt-4.7.1/mkspecs/common/linux.conf \
		/opt/qt-4.7.1/mkspecs/common/qws.conf \
		/opt/qt-4.7.1/mkspecs/qconfig.pri \
		/opt/qt-4.7.1/mkspecs/features/qt_functions.prf \
		/opt/qt-4.7.1/mkspecs/features/qt_config.prf \
		/opt/qt-4.7.1/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.7.1/mkspecs/features/default_pre.prf \
		/opt/qt-4.7.1/mkspecs/features/release.prf \
		/opt/qt-4.7.1/mkspecs/features/default_post.prf \
		/opt/qt-4.7.1/mkspecs/features/warn_on.prf \
		/opt/qt-4.7.1/mkspecs/features/qt.prf \
		/opt/qt-4.7.1/mkspecs/features/unix/thread.prf \
		/opt/qt-4.7.1/mkspecs/features/moc.prf \
		/opt/qt-4.7.1/mkspecs/features/resources.prf \
		/opt/qt-4.7.1/mkspecs/features/uic.prf \
		/opt/qt-4.7.1/mkspecs/features/yacc.prf \
		/opt/qt-4.7.1/mkspecs/features/lex.prf \
		/opt/qt-4.7.1/mkspecs/features/include_source_dir.prf \
		ui_des.pro
QMAKE_TARGET  = ui_des
DESTDIR       = 
TARGET        = ui_des

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_config_widget.h ui_keyboard.h ui_mesdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ui_des.pro  /opt/qt-4.7.1/mkspecs/qws/linux-arm-g++/qmake.conf /opt/qt-4.7.1/mkspecs/common/g++.conf \
		/opt/qt-4.7.1/mkspecs/common/unix.conf \
		/opt/qt-4.7.1/mkspecs/common/linux.conf \
		/opt/qt-4.7.1/mkspecs/common/qws.conf \
		/opt/qt-4.7.1/mkspecs/qconfig.pri \
		/opt/qt-4.7.1/mkspecs/features/qt_functions.prf \
		/opt/qt-4.7.1/mkspecs/features/qt_config.prf \
		/opt/qt-4.7.1/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.7.1/mkspecs/features/default_pre.prf \
		/opt/qt-4.7.1/mkspecs/features/release.prf \
		/opt/qt-4.7.1/mkspecs/features/default_post.prf \
		/opt/qt-4.7.1/mkspecs/features/warn_on.prf \
		/opt/qt-4.7.1/mkspecs/features/qt.prf \
		/opt/qt-4.7.1/mkspecs/features/unix/thread.prf \
		/opt/qt-4.7.1/mkspecs/features/moc.prf \
		/opt/qt-4.7.1/mkspecs/features/resources.prf \
		/opt/qt-4.7.1/mkspecs/features/uic.prf \
		/opt/qt-4.7.1/mkspecs/features/yacc.prf \
		/opt/qt-4.7.1/mkspecs/features/lex.prf \
		/opt/qt-4.7.1/mkspecs/features/include_source_dir.prf \
		/opt/qt-4.7.1/lib/libQtGui.prl \
		/opt/qt-4.7.1/lib/libQtNetwork.prl \
		/opt/qt-4.7.1/lib/libQtCore.prl
	$(QMAKE) -o Makefile ui_des.pro
/opt/qt-4.7.1/mkspecs/common/g++.conf:
/opt/qt-4.7.1/mkspecs/common/unix.conf:
/opt/qt-4.7.1/mkspecs/common/linux.conf:
/opt/qt-4.7.1/mkspecs/common/qws.conf:
/opt/qt-4.7.1/mkspecs/qconfig.pri:
/opt/qt-4.7.1/mkspecs/features/qt_functions.prf:
/opt/qt-4.7.1/mkspecs/features/qt_config.prf:
/opt/qt-4.7.1/mkspecs/features/exclusive_builds.prf:
/opt/qt-4.7.1/mkspecs/features/default_pre.prf:
/opt/qt-4.7.1/mkspecs/features/release.prf:
/opt/qt-4.7.1/mkspecs/features/default_post.prf:
/opt/qt-4.7.1/mkspecs/features/warn_on.prf:
/opt/qt-4.7.1/mkspecs/features/qt.prf:
/opt/qt-4.7.1/mkspecs/features/unix/thread.prf:
/opt/qt-4.7.1/mkspecs/features/moc.prf:
/opt/qt-4.7.1/mkspecs/features/resources.prf:
/opt/qt-4.7.1/mkspecs/features/uic.prf:
/opt/qt-4.7.1/mkspecs/features/yacc.prf:
/opt/qt-4.7.1/mkspecs/features/lex.prf:
/opt/qt-4.7.1/mkspecs/features/include_source_dir.prf:
/opt/qt-4.7.1/lib/libQtGui.prl:
/opt/qt-4.7.1/lib/libQtNetwork.prl:
/opt/qt-4.7.1/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile ui_des.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ui_des1.0.0 || $(MKDIR) .tmp/ui_des1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ui_des1.0.0/ && $(COPY_FILE) --parents mainwindow.h config_widget.h keyboarddlg.h mylinedit.h spi.h mywidget.h commmacro.h valve.h mypid.h mybutton.h myi2c.h mesdialog.h pwmqthread.h .tmp/ui_des1.0.0/ && $(COPY_FILE) --parents image.qrc .tmp/ui_des1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp config_widget.cpp keyboarddlg.cpp mylinedit.cpp mywidget.cpp valve.cpp mypid.cpp mybutton.cpp myi2c.cpp mesdialog.cpp pwmqthread.cpp .tmp/ui_des1.0.0/ && $(COPY_FILE) --parents mainwindow.ui config_widget.ui keyboard.ui mesdialog.ui .tmp/ui_des1.0.0/ && (cd `dirname .tmp/ui_des1.0.0` && $(TAR) ui_des1.0.0.tar ui_des1.0.0 && $(COMPRESS) ui_des1.0.0.tar) && $(MOVE) `dirname .tmp/ui_des1.0.0`/ui_des1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ui_des1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_config_widget.cpp moc_keyboarddlg.cpp moc_mylinedit.cpp moc_mywidget.cpp moc_mybutton.cpp moc_mesdialog.cpp moc_pwmqthread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_config_widget.cpp moc_keyboarddlg.cpp moc_mylinedit.cpp moc_mywidget.cpp moc_mybutton.cpp moc_mesdialog.cpp moc_pwmqthread.cpp
moc_mainwindow.cpp: config_widget.h \
		keyboarddlg.h \
		ui_keyboard.h \
		mylinedit.h \
		commmacro.h \
		mywidget.h \
		mesdialog.h \
		valve.h \
		mypid.h \
		mybutton.h \
		myi2c.h \
		pwmqthread.h \
		spi.h \
		mainwindow.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_config_widget.cpp: keyboarddlg.h \
		ui_keyboard.h \
		mylinedit.h \
		commmacro.h \
		mywidget.h \
		mesdialog.h \
		config_widget.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) config_widget.h -o moc_config_widget.cpp

moc_keyboarddlg.cpp: ui_keyboard.h \
		keyboarddlg.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) keyboarddlg.h -o moc_keyboarddlg.cpp

moc_mylinedit.cpp: mylinedit.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) mylinedit.h -o moc_mylinedit.cpp

moc_mywidget.cpp: mywidget.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) mywidget.h -o moc_mywidget.cpp

moc_mybutton.cpp: mybutton.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) mybutton.h -o moc_mybutton.cpp

moc_mesdialog.cpp: mesdialog.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) mesdialog.h -o moc_mesdialog.cpp

moc_pwmqthread.cpp: commmacro.h \
		mywidget.h \
		spi.h \
		config_widget.h \
		keyboarddlg.h \
		ui_keyboard.h \
		mylinedit.h \
		mesdialog.h \
		pwmqthread.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) pwmqthread.h -o moc_pwmqthread.cpp

compiler_rcc_make_all: qrc_image.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_image.cpp
qrc_image.cpp: image.qrc \
		png/bt_model_d_english.png \
		png/bt_zy.png \
		png/lcd_back.png \
		png/conf.png \
		png/bt_change_manu_chinese.png \
		png/gct_ied_yellow.png \
		png/bt_on.png \
		png/bt_in_clicked.jpg \
		png/bt_in_def.jpg \
		png/log_def.png \
		png/gct_ied_blank.png \
		png/logo_right.png \
		png/gct_ied_red.png \
		png/bt_stop_clicked.jpg \
		png/config_ui.jpg \
		png/main_ui.jpg \
		png/gct_ied_green.png \
		png/config_def.jpg \
		png/bt_model_s_chinses.png \
		png/start.jpg \
		png/centpic.jpg \
		png/l_english.jpg \
		png/homechoose.png \
		png/bt_model_s_english.png \
		png/l_chinese.jpg \
		png/bt_off.png \
		png/bt_change_auto_english.png \
		png/leftpic.jpg \
		png/config_uinew.jpg \
		png/empty_background.jpg \
		png/rightpic.jpg \
		png/log_clicked.png \
		png/bt_model_d_chinses.png \
		png/homedefault.png \
		png/bt_stop_def.jpg \
		png/bt_out_def.jpg \
		png/stop.jpg \
		png/reset-click.png \
		png/bt_out_clicked.jpg \
		png/bt_change_auto_chinese.png \
		png/reset-default.png \
		png/backpic.jpg \
		png/config_clicked.jpg \
		png/bt_change_manu_english.png \
		png/bt_lighe.png
	/opt/qt-4.7.1/bin/rcc -name image image.qrc -o qrc_image.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_config_widget.h ui_keyboard.h ui_mesdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_config_widget.h ui_keyboard.h ui_mesdialog.h
ui_mainwindow.h: mainwindow.ui
	/opt/qt-4.7.1/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_config_widget.h: config_widget.ui \
		mylinedit.h
	/opt/qt-4.7.1/bin/uic config_widget.ui -o ui_config_widget.h

ui_keyboard.h: keyboard.ui
	/opt/qt-4.7.1/bin/uic keyboard.ui -o ui_keyboard.h

ui_mesdialog.h: mesdialog.ui
	/opt/qt-4.7.1/bin/uic mesdialog.ui -o ui_mesdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		config_widget.h \
		keyboarddlg.h \
		ui_keyboard.h \
		mylinedit.h \
		commmacro.h \
		mywidget.h \
		mesdialog.h \
		valve.h \
		mypid.h \
		mybutton.h \
		myi2c.h \
		pwmqthread.h \
		spi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		config_widget.h \
		keyboarddlg.h \
		ui_keyboard.h \
		mylinedit.h \
		commmacro.h \
		mywidget.h \
		mesdialog.h \
		valve.h \
		mypid.h \
		mybutton.h \
		myi2c.h \
		pwmqthread.h \
		spi.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

config_widget.o: config_widget.cpp config_widget.h \
		keyboarddlg.h \
		ui_keyboard.h \
		mylinedit.h \
		commmacro.h \
		mywidget.h \
		mesdialog.h \
		ui_config_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config_widget.o config_widget.cpp

keyboarddlg.o: keyboarddlg.cpp keyboarddlg.h \
		ui_keyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keyboarddlg.o keyboarddlg.cpp

mylinedit.o: mylinedit.cpp mylinedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mylinedit.o mylinedit.cpp

mywidget.o: mywidget.cpp mywidget.h \
		commmacro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mywidget.o mywidget.cpp

valve.o: valve.cpp valve.h \
		commmacro.h \
		mywidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o valve.o valve.cpp

mypid.o: mypid.cpp mypid.h \
		commmacro.h \
		mywidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mypid.o mypid.cpp

mybutton.o: mybutton.cpp mybutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mybutton.o mybutton.cpp

myi2c.o: myi2c.cpp myi2c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myi2c.o myi2c.cpp

mesdialog.o: mesdialog.cpp mesdialog.h \
		ui_mesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mesdialog.o mesdialog.cpp

pwmqthread.o: pwmqthread.cpp pwmqthread.h \
		commmacro.h \
		mywidget.h \
		spi.h \
		config_widget.h \
		keyboarddlg.h \
		ui_keyboard.h \
		mylinedit.h \
		mesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pwmqthread.o pwmqthread.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_config_widget.o: moc_config_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_config_widget.o moc_config_widget.cpp

moc_keyboarddlg.o: moc_keyboarddlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keyboarddlg.o moc_keyboarddlg.cpp

moc_mylinedit.o: moc_mylinedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mylinedit.o moc_mylinedit.cpp

moc_mywidget.o: moc_mywidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mywidget.o moc_mywidget.cpp

moc_mybutton.o: moc_mybutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mybutton.o moc_mybutton.cpp

moc_mesdialog.o: moc_mesdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mesdialog.o moc_mesdialog.cpp

moc_pwmqthread.o: moc_pwmqthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pwmqthread.o moc_pwmqthread.cpp

qrc_image.o: qrc_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_image.o qrc_image.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

